apiVersion: v1
kind: Service
metadata:
  name: client-port
spec:
  type: ClusterIP
  ports:
    - name: app-port
      port: 8080
      targetPort: 8080
    - name: debug-port
      port: 5005
      targetPort: 5005
  selector:
    app: demo-app
---
#localhost:80
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo-app
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-port
                port:
                  number: 8080
  ingressClassName: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: demo-image
          livenessProbe:
            httpGet:
              port: 9000
              path: /actuator/health/liveness
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 9000
              path: /actuator/health/readiness
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          envFrom:
            - configMapRef:
                name: demo-config
          ports:
            - containerPort: 8080
              name: app-port
            - containerPort: 5005
              name: debug-port
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  test.name: Batman