apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: k8sdemo
build:
  artifacts:
    - image: demo-image
      jib: { }
deploy:
  kubectl:
    manifests:
      - deployment.yaml
#portForward:
#  - resourceType: service
#    resourceName: client-port
#    port: 8080
