apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: k8sdemo
build:
  tagPolicy:
    customTemplate:
      template: "{{.GIT}}-{{.DATE}}"
      components:
        - name: GIT
          gitCommit: { }
        - name: DATE
          dateTime:
            format: 2006-01-02_15-04-05
            timezone: UTC
  artifacts:
    - image: demo-image
      jib: { }
      hooks:
        before:
          - command: [ "cmd.exe","/C","remove_images.bat" ]
            os: [ windows ]
deploy:
  kustomize:
    paths:
      - deployment/overlays/local
#  kubectl:
#    manifests:
#      - deployment/postgres-deployment.yaml
#      - deployment/deployment.yaml
#portForward:
#  - resourceType: service
#    resourceName: client-port
#    port: 8080
