management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  server:
    port: 9000
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    root: info
    org.hibernate: debug
server:
  shutdown: graceful
spring:
  application:
    name: demo-application
  cloud:
    kubernetes:
      config:
        name: config-name
        namespace: default-namespace
        sources:
          - name: demo-config


