apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: dev
namePrefix: dev-

configMapGenerator:
  - name: demo-config
    files:
      - configs/application.yml

resources:
  - ../../base

patchesStrategicMerge:
  - patch-app-deployment.yaml

patchesJson6902:
  - target:
      group: networking.k8s.io
      kind: Ingress
      name: ingress-demo-app
      version: v1
    patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /dev/(.*)