apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  replicas: 1
  template:
#    metadata:
    #      annotations:
    #        vault.hashicorp.com/role: "vault-app"
    #        vault.hashicorp.com/agent-inject: "true"
    #        vault.hashicorp.com/agent-inject-secret-dbpass: "dev/database/config"
    spec:
      containers:
        - name: demo-app
          image: demo-image