apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: local
namePrefix: local-

#configMapGenerator:
#  - name: demo-config
#    behavior: create
#    files:
#      - configs/application.yml

resources:
  - ../../base
  - app-configmap.yaml

components:
  - ../../components/postgres