apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: local
namePrefix: local-

configMapGenerator:
  - name: demo-config
    files:
      - configs/application.yml

resources:
  - ../../base

components:
  - ../../components/postgres