apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  spring.datasource.url: jdbc:postgresql://postgres-port:5432/postgres
  spring.datasource.username: admin
  spring.datasource.password: admin123