apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - client-port-service.yaml
  - client-port-ingress.yaml
  - app-configmap.yaml
  - app-deployment.yaml
commonAnnotations:
  name: demo-app
  version: 1.0.0kubec
