apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - postgres-configmap.yaml
  - postgres-pv.yaml
  - postgres-pvc.yaml
  - postgres-port-service.yaml
  - postgres-deployment.yaml